base_url = "https://cheri.dev"
title = "Ali Chaayb - Personal Website"
description = " This is the personal website showcasing Ali chaayb's work, interests, and more..."
compile_sass = true
build_search_index = false
taxonomies = [
    {name = "categories", feed = false},
    {name = "tags", feed = false},
]
[markdown]
highlight_code = true
[extra]
name = "Ali Chaayb"
id = "cheri.dev"
bio = "Backend/Devops Engineer (≧⌣≦)"
avatar = "img/achaayb.jpeg"
links = [
    { name = "GitHub", icon = "github", url = "https://github.com/achaayb" },
    { name = "Linkedin", icon = "linkedin", url = "https://www.linkedin.com/in/achaayb/" },
    { name = "Email", icon = "email", url = "mailto:achaayb.cheri.dev@gmail.com" }
]
feed_filename = "rss.xml"
homepage_layout = "about"
recent_max = 15
recent_more = true
recent_more_text = "more »"
sections = [
    { name = "Projects", path = "/projects", is_external = false },
    { name = "Blog", path = "/blog", is_external = false },
    { name = "About", path = "/about", is_external = false }
]
blog_section_path = "/blog"
nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","
display_id = true                  
blog_categorized = true              
blur_effect = true                    
back_to_top = true                    
toc = true                             
copy = true                            
comment = false                        
display_tags = true                     
truncate_summary = false               
outdate_alert = false                  
outdate_alert_days = 120
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."
footer_copyright = "© 2024 cheri.dev"
footer_credits = false                 # Whether to show "powered by zola and serene" in footer
not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"